import { defineConfig } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier";
import noStoreGetStateInRender from "./eslint-rules/no-store-getstate-in-render.mjs";
import noUnguardedNotification from "./eslint-rules/no-unguarded-notification.mjs";
import noDirectSentryCapture from "./eslint-rules/no-direct-sentry-capture.mjs";

const localRules = {
  plugins: {
    local: {
      rules: {
        "no-store-getstate-in-render": noStoreGetStateInRender,
        "no-unguarded-notification": noUnguardedNotification,
        "no-direct-sentry-capture": noDirectSentryCapture,
      },
    },
  },
  rules: {
    "local/no-store-getstate-in-render": "error",
    "local/no-unguarded-notification": "error",
    "local/no-direct-sentry-capture": "error",
  },
};

const eslintConfig = defineConfig([
  {
    ignores: [
      ".claude/**",
      ".next/**",
      ".claude/worktrees/**",
      ".worktrees/**",
      "coverage/**",
      // generated by scripts/copy-maplibre-worker.mjs (postinstall) — vendored, not authored
      "public/maplibre-gl-worker.mjs",
      "public/maplibre-gl-shared.mjs",
    ],
  },
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
  {
    settings: {
      react: { version: "19" },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  localRules,
  {
    files: ["scripts/**/*.mjs", "scripts/**/*.js", "scripts/**/*.ts"],
    rules: { "no-console": "off" },
  },
]);

export default eslintConfig;
