import type { Venue } from "../types";

export const VENUES: Venue[] = [
  {
    id: "msg",
    name: "Madison Square Garden",
    shortName: "MSG",
    lat: 40.7505,
    lng: -73.9934,
    tier: "tier1",
    radiusKm: 0.5,
    cameraIds: ["6a85384f-d82e-4bff-b5f1-15c22cca70e6"],
    espnSports: ["basketball/nba", "hockey/nhl"],
    tmId: "KovZpZAEdntA",
  },
  {
    id: "yankee-stadium",
    name: "Yankee Stadium",
    shortName: "Yankee Stadium",
    lat: 40.8296,
    lng: -73.9262,
    tier: "tier1",
    radiusKm: 0.5,
    cameraIds: ["ad051a78-9c50-43b3-bb71-83b091acd818"],
    espnSports: ["baseball/mlb"],
    espnHomeTeams: ["New York Yankees"],
    tmId: "KovZpZAEkAkA",
  },
  {
    id: "citi-field",
    name: "Citi Field",
    shortName: "Citi Field",
    lat: 40.7571,
    lng: -73.8458,
    tier: "tier1",
    radiusKm: 1.0,
    cameraIds: ["39b42007-16d8-4302-8b8c-602bbb9e9683"],
    espnSports: ["baseball/mlb"],
    espnHomeTeams: ["New York Mets"],
    tmId: "KovZpZAEkdoA",
  },
  {
    id: "barclays-center",
    name: "Barclays Center",
    shortName: "Barclays",
    lat: 40.6826,
    lng: -73.9754,
    tier: "tier1",
    radiusKm: 0.5,
    cameraIds: [],
    espnSports: ["basketball/nba", "hockey/nhl"],
    tmId: "KovZpZAEAbEA",
  },
  {
    id: "metlife-stadium",
    name: "MetLife Stadium",
    shortName: "MetLife",
    lat: 40.8136,
    lng: -74.0745,
    tier: "tier1",
    radiusKm: 1.0,
    cameraIds: [],
    espnSports: ["football/nfl"],
  },
  {
    id: "madison-sq-park",
    name: "Madison Square Park",
    shortName: "Madison Sq Park",
    lat: 40.7425,
    lng: -73.9878,
    tier: "tier3",
    radiusKm: 0.3,
    cameraIds: [],
  },
  {
    id: "central-park-summerstage",
    name: "Central Park SummerStage",
    shortName: "SummerStage",
    lat: 40.7729,
    lng: -73.9693,
    tier: "tier2",
    radiusKm: 0.5,
    cameraIds: [],
    tmId: "KovZpZAEdFtA",
  },
];

export function getVenueById(id: string): Venue | undefined {
  return VENUES.find((v) => v.id === id);
}
